import axios from "axios";
import { Fragment } from "react";
import getTitles from "../../helpers/dataCenter";
import Head from "next/head";
import CategoryPageLayout from "../../components/layout/categorypagelayout/CategoryPageLayout";
const category = (props) => {
  const categoryData = props.data.results;
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CategoryPageLayout>hi</CategoryPageLayout>
    </Fragment>
  );
};

export default category;

export async function getStaticProps(context) {
  const category = context.params.category;
  const baseUrl = `https://api.nytimes.com/svc/topstories/v2/${category}.json?api-key=EhgvtA3WE0sRHZeL6sQ8LPFZtn2CtGFz`;
  const data = await axios.get(baseUrl);
  return {
    props: {
      data: data.data,
    },
  };
}
export async function getStaticPaths() {
  const sections = await getTitles();
  const paths = sections.map((section) => ({ params: { category: section } }));
  return {
    paths: paths,
    fallback: "blocking",
  };
}
