import Head from "next/head";
import MainPageLayout from "../components/layout/mainpagelayout/MainPageLayout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainPageLayout></MainPageLayout>

      <footer></footer>
    </div>
  );
}
