import axios from "axios";
import Head from "next/head";
import { Fragment } from "react";
import MainPageLayout from "../components/layout/mainpagelayout/MainPageLayout";
import MainPage from "../components/mainPage/MainPage";

export default function Home(props) {
  const content = props.content;

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainPageLayout content={content}>
        <MainPage content={content} />
      </MainPageLayout>
    </Fragment>
  );
}
export async function getStaticProps() {
  const baseUrl =
    "https://api.nytimes.com/svc/topstories/v2/home.json?api-key=EhgvtA3WE0sRHZeL6sQ8LPFZtn2CtGFz";
  const data = await axios.get(baseUrl);
  return {
    props: {
      content: data.data,
    },
    revalidate: 100,
  };
}
